[package]
name = "katex_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
katex = "0.4.3"
tl = "0.6.2"
html-escape="0.2.9"
